### ISSUE TITLE
支持拉起微信客服吗

### ISSUE THREAD

**Issue by conkyliu** [chenqingze/capacitor-wechat-sdk#1]

**Comment by chenqingze** [comment]
自用项目，目前不支持，我的项目没有用到，你可以自己修改一下，增加相关的ts接口和对应的native方法就好了，参考：
https://capacitorjs.com/docs/plugins/workflow和https://developers.weixin.qq.com/doc/oplatform/Mobile_App/APP_launch_wechat_customer_service.html

如果不着急的话，正月十五后开班我增加上。

**Comment by chenqingze** [comment]
拉起微信客服已增加至develop分支，未测试～拉去develop分支代码自行测试

**Comment by conkyliu** [comment]
> 拉起微信客服已增加至develop分支，未测试～拉去develop分支代码自行测试

好的，感谢！

**Comment by chenqingze** [comment]
代码已合并到main 分支，我关闭了。如有问题再开新的issue 吧～
