### ISSUE TITLE
sendAuthRequest, ERROR: fail to load Keychain status:-25300, keyData null:1

### ISSUE THREAD

**Issue by yunter** [chenqingze/capacitor-wechat-sdk#2]
确认 Appid and UniversalLink 无误，自检也通过

but 实际调用时，无法正常返回，日志如下

` WeChatSDK: wxlog:set property list `
` WeChatSDK: wxlog:Error:fail to load Keychain status:-25300, keyData null:1 `
` WeChatSDK: wxlog:token[(null)] is null `
` WeChatSDK: wxlog:launch app with ul only success `
` WeChatSDK: wxlog:launch app with universal link, ret:1 `
` WeChatSDK: wxlog:req:<SendAuthReq: 0x282b26bb0>, `cid:495557e48fb42282ffc0ef75d37606b29f7aad68f4dd380a4c511b77aa9f13d3 `

试过网上各种方法，如：官网社区(https://developers.weixin.qq.com/community/develop/doc/000e4a880f8058c5e99ac4f2a5b400?_at=1644489439188)，简书（https://www.jianshu.com/p/f9948d08d53a）
没搞定，求教谢谢

**Comment by chenqingze** [comment]
0、拉取main 分支最新代码试试
1、[参考微信官方配置[UniversalLink]并配置URL scheme](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/iOS.html)
2、在你的工程文件中选择 Build Setting，在"Other Linker Flags"中加入"-ObjC -all_load"
3、修改app/appDelegate.swift，增加或修改下面回调处理：
```
 func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {    
      return WechatSDKApplicationDelegate.sharedInstance.application(application,continue: userActivity, restorationHandler: restorationHandler)    
       // return ApplicationDelegateProxy.shared.application(application, continue: userActivity, restorationHandler: restorationHandler)    
}
```
4、修改 capacitor.config.ts 或capacitor.config.json文件，增加微信相关配置参数
```
const config: CapacitorConfig = {
  mchid: '123456', // 商户id
  wechatAppId: 'wxd***c1fdsfsfs7f4f***', // 应用从微信开放平台官方网站申请到的合法appID
  wechatUniversalLink: 'https://com.***.***/' // UniversalLink
};
```
5、安卓还需要修改[capacitor-wechat-sdk](https://github.com/chenqingze/capacitor-wechat-sdk)/[android](https://github.com/chenqingze/capacitor-wechat-sdk/tree/main/android)/build.gradle文件：
<img width="674" alt="image" src="https://user-images.githubusercontent.com/8285776/153450222-5326f98c-d225-45f2-b609-dcfaeecacd50.png">

**Comment by chenqingze** [comment]
另外自检函数和SendReq不可以同时调用，尝试注释掉自检函数再次调试。

**Comment by yunter** [comment]
> 0、拉取main 分支最新代码试试 1、[参考微信官方配置[UniversalLink]并配置URL scheme](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/iOS.html) 2、在你的工程文件中选择 Build Setting，在"Other Linker Flags"中加入"-ObjC -all_load" 3、修改app/appDelegate.swift，增加或修改下面回调处理：
> 
> ```
>  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {    
>       return WechatSDKApplicationDelegate.sharedInstance.application(application,continue: userActivity, restorationHandler: restorationHandler)    
>        // return ApplicationDelegateProxy.shared.application(application, continue: userActivity, restorationHandler: restorationHandler)    
> }
> ```
> 
> 4、修改 capacitor.config.ts 或capacitor.config.json文件，增加微信相关配置参数
> 
> ```
> const config: CapacitorConfig = {
>   mchid: '123456', // 商户id
>   wechatAppId: 'wxd***c1fdsfsfs7f4f***', // 应用从微信开放平台官方网站申请到的合法appID
>   wechatUniversalLink: 'https://com.***.***/' // UniversalLink
> };
> ```
> 
> 5、安卓还需要修改[capacitor-wechat-sdk](https://github.com/chenqingze/capacitor-wechat-sdk)/[android](https://github.com/chenqingze/capacitor-wechat-sdk/tree/main/android)/build.gradle文件： <img alt="image" width="674" src="https://user-images.githubusercontent.com/8285776/153450222-5326f98c-d225-45f2-b609-dcfaeecacd50.png">

搞定了，非常感谢，很细致的指导。我修了appDelegate，一次通过。
