### ISSUE TITLE
js项目中如何使用

### ISSUE THREAD

**Issue by estoi** [chenqingze/capacitor-wechat-sdk#3]
@chenqingze

**Comment by estoi** [comment]
```json
{"save":false,"callbackId":"40723669","pluginId":"WechatSDK","methodName":"sendAuthRequest","success":false,"error":{"message":"未知错误","code":"-6"}}
```
```js
import { WechatSDK } from "@capacitor/wechat-sdk/src";
export default {
  setup() {
    onMounted(() => {
      const scope = "snsapi_userinfo",
        state = "_" + +new Date();
      WechatSDK.sendAuthRequest({ scope, state })
        .then((res) => {
          alert(JSON.stringify(res));
        })
        .catch((err) => {
          alert(JSON.stringify(err));
        }).finally(com => {
          alert(JSON.stringify(com))
        })
    });
  },
};
</script>
```
调用sendAuthRequest报未知错误

**Comment by chenqingze** [comment]
主体项目接口是按照capacitor的方式使用ts写的， 没尝试过js调用。
如果想尝试js调用，可以尝试参考本项目编译后 capacitor-wechat-sdk/dist/** 下的文件。
编译方式，项目根目录执行：
`npm run build`

**Comment by chenqingze** [comment]
> ```json
> {"save":false,"callbackId":"40723669","pluginId":"WechatSDK","methodName":"sendAuthRequest","success":false,"error":{"message":"未知错误","code":"-6"}}
> ```
> 
> ```js
> import { WechatSDK } from "@capacitor/wechat-sdk/src";
> export default {
>   setup() {
>     onMounted(() => {
>       const scope = "snsapi_userinfo",
>         state = "_" + +new Date();
>       WechatSDK.sendAuthRequest({ scope, state })
>         .then((res) => {
>           alert(JSON.stringify(res));
>         })
>         .catch((err) => {
>           alert(JSON.stringify(err));
>         }).finally(com => {
>           alert(JSON.stringify(com))
>         })
>     });
>   },
> };
> </script>
> ```
> 
> 调用sendAuthRequest报未知错误 

   
[另外仔细阅读下readme](https://github.com/chenqingze/capacitor-wechat-sdk#readme)，
1.保证ios或android相关配置正确
2.有些参数是在capacitor.config.ts 或capacitor.config.json文件中读取的，如果没有可以自己新建一个。
