### ISSUE TITLE
android端调用授权报错

### ISSUE THREAD

**Issue by estoi** [chenqingze/capacitor-wechat-sdk#4]
@chenqingze 

android studio 直接run到手机上测试的

使用axios做http请求没问题，这个插件提示发送请求失败

```js
error: {"save":false,"callbackId":"33083872","pluginId":"WechatSDK","methodName":"sendAuthRequest","success":false,"error":{"message":"发送请求失败"}}
```

**Comment by chenqingze** [comment]
1、[检查参数配置](https://github.com/chenqingze/capacitor-wechat-sdk#%E5%8F%82%E6%95%B0%E9%85%8D%E7%BD%AE)
2、[检查android配置](https://github.com/chenqingze/capacitor-wechat-sdk#android%E9%85%8D%E7%BD%AE)
3、apk 使用keystore进行签名

**Comment by estoi** [comment]
`sendAuthRequest `调用成功了，如何获取用户信息，如openid？目前then回调只有一个操作成功的结果 @chenqingze

**Comment by chenqingze** [comment]
> `sendAuthRequest `调用成功了，如何获取用户信息，如openid？目前then回调只有一个操作成功的结果 @chenqingze

稍等，之前android有些修改没提交

**Comment by estoi** [comment]
> 

谢谢啦

**Comment by chenqingze** [comment]
> > 
> 
> 谢谢啦

重新拉取一下主分支试试！
拿到返回的code去换取token就好了,[参考微信官方文档](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/WeChat_Login/Development_Guide.html)
因为未经测试就提交代码了，麻烦告知我是否可以正常调起使用。

**Comment by estoi** [comment]
OK了
