### ISSUE TITLE
Android10上可以拉起授权，Android11上拉起授权报“发送请求失败”

### ISSUE THREAD

**Issue by estoi** [chenqingze/capacitor-wechat-sdk#5]
@chenqingze

**Comment by estoi** [comment]
证书都配置了，但是在android11系统上报错了

**Comment by chenqingze** [comment]
参考下面链接，看看能不能解决 ：
https://open.weixin.qq.com/cgi-bin/announce?action=getannouncement&key=11600155960jI9EY&version=&lang=&token=

**Comment by estoi** [comment]
> 参考下面链接，看看能不能解决 ： https://open.weixin.qq.com/cgi-bin/announce?action=getannouncement&key=11600155960jI9EY&version=&lang=&token=

可以拉起了
