### ISSUE TITLE
这个capacitor4.0可以直接用吗,我看配置里是3.0的

### ISSUE THREAD

**Issue by lilao6** [chenqingze/capacitor-wechat-sdk#7]

**Comment by chenqingze** [comment]
3.0-4.0变化比较小。clone项目到本地参考[官方文档] (https://capacitorjs.com/docs/updating/4-0) 升级即可使用。

**Comment by lilao6** [comment]
> 3.0-4.0变化比较小。clone项目到本地参考[官方文档] (https://capacitorjs.com/docs/updating/4-0) 升级即可使用。

嗯,弄到本地了,成功运行,谢了
