### ISSUE TITLE
ios 怎么判断是wechat 的userActivity呢

### ISSUE THREAD

**Issue by conkyliu** [chenqingze/capacitor-wechat-sdk#8]
添加这一行，
 func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {    
      return WechatSDKApplicationDelegate.sharedInstance.application(application,continue: userActivity, restorationHandler: restorationHandler)    
       // return ApplicationDelegateProxy.shared.application(application, continue: userActivity, restorationHandler: restorationHandler)    
}
函数里面存在这一个，怎么判断是微信插件才执行上面的return
`     return ApplicationDelegateProxy.shared.application(application, continue: userActivity, restorationHandler: restorationHandler)
           
  `

**Comment by chenqingze** [comment]
判断url是否包含对应的appid
```swift
let webpageURL = userActivity.webpageURL else {
            return false
 }
if webpageURL.contains(微信appid) {
 // wechat process
}else{ 
 // other process
}
```

**Comment by conkyliu** [comment]
iOS 接入登录无回调，分享，支付也是。可以跳到微信界面。
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/26617741/192988525-d836fdf5-a88d-4668-8dbe-f4e674880b2b.png">

**Comment by conkyliu** [comment]
支付是正常的，登录跳去微信点确定登录后回到app没有反应，打印也无记录 ，点分享一直现在正在连接然后回到app。

**Comment by conkyliu** [comment]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/26617741/192990675-22a497c3-2617-4bfe-b2cd-2be5a909446b.png">
打印日志只看到wechat code1 这一块输出，是不是UL配置有误导致呢？

**Comment by conkyliu** [comment]
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/26617741/193000579-c3a7d080-bda4-4d15-85a1-ee07db546c31.png">
wechat userActivity Optional(https://appurl.lig***ym.cn/wxc0***0b613eb4/oauth?code=083jKD1****mBD3w3uEQHa1jKD1c&state=_2022-09-29+18%3A09)
微信响应回调
微信响应回调码解析 WXErrCode
⚡️  TO JS {"state":"_2022-09-29+18%3A09","errCode":"0","message":"操作成功"}

**Comment by chenqingze** [comment]
> iOS 接入登录无回调，分享，支付也是。可以跳到微信界面。 <img alt="image" width="1074" src="https://user-images.githubusercontent.com/26617741/192988525-d836fdf5-a88d-4668-8dbe-f4e674880b2b.png">

不是配置的问题，用的angular或ionic吗？如果是并且不回调，关注下ngZone  。确保ts的调用的代码逻辑在同一个zone上下文内。具体请参考:[Angular相关章节](https://angular.cn/guide/zone)
```ts
zone.run(() => {
  // now you are in a zone
 // 代码逻辑保证在同一zone
});
```

**Comment by conkyliu** [comment]
> > iOS 接入登录无回调，分享，支付也是。可以跳到微信界面。 <img alt="image" width="1074" src="https://user-images.githubusercontent.com/26617741/192988525-d836fdf5-a88d-4668-8dbe-f4e674880b2b.png">
> 
> 不是配置的问题，用的angular或ionic吗？如果是并且不回调，关注下ngZone 。确保ts的调用的代码逻辑在同一个zone上下文内。具体请参考:[Angular相关章节](https://angular.cn/guide/zone)
> 
> ```ts
> zone.run(() => {
>   // now you are in a zone
>  // 代码逻辑保证在同一zone
> });
> ```

是ios那边下发UL延迟问题，后面UL都通了，ios端登录后没有返回code给js，这边手动加入了。
